/**
 * Action type constants — single source of truth for all reducer action types.
 * Eliminates string literals across actions.js, reducers, and DATA_ACTIONS.
 */

// ── Provider ──────────────────────────────────────────────────
export const SET_API_KEY = 'SET_API_KEY';
export const CLEAR_API_KEY = 'CLEAR_API_KEY';
export const SET_PROVIDER_KEY = 'SET_PROVIDER_KEY';
export const SET_ACTIVE_PROVIDER = 'SET_ACTIVE_PROVIDER';
export const SET_ACTIVE_MODEL = 'SET_ACTIVE_MODEL';
export const SET_GRADING_MODEL = 'SET_GRADING_MODEL';
export const SET_CUSTOM_BASE_URL = 'SET_CUSTOM_BASE_URL';
export const SET_CUSTOM_MODEL_NAME = 'SET_CUSTOM_MODEL_NAME';
export const SET_COMPAT_PRESET = 'SET_COMPAT_PRESET';
export const SET_FETCHED_MODELS = 'SET_FETCHED_MODELS';

// ── Learning Path ────────────────────────────────────────────
export const ADD_LEARNING_PATH = 'ADD_LEARNING_PATH';
export const UPDATE_LEARNING_PATH = 'UPDATE_LEARNING_PATH';
export const REMOVE_LEARNING_PATH = 'REMOVE_LEARNING_PATH';
export const UNDO_REMOVE_LEARNING_PATH = 'UNDO_REMOVE_LEARNING_PATH';
export const SET_PATH_UNIT_SYLLABUS = 'SET_PATH_UNIT_SYLLABUS';
export const UPDATE_PATH_COVERAGE = 'UPDATE_PATH_COVERAGE';
export const EXTEND_LEARNING_PATH = 'EXTEND_LEARNING_PATH';
export const REORDER_PATH_UNITS = 'REORDER_PATH_UNITS';
export const UPDATE_PATH_UNIT = 'UPDATE_PATH_UNIT';
export const ARCHIVE_LEARNING_PATH = 'ARCHIVE_LEARNING_PATH';
export const UNARCHIVE_LEARNING_PATH = 'UNARCHIVE_LEARNING_PATH';

// ── Syllabus ──────────────────────────────────────────────────
export const ADD_SYLLABUS = 'ADD_SYLLABUS';
export const EXTEND_SYLLABUS_LESSONS = 'EXTEND_SYLLABUS_LESSONS';
export const REMOVE_SYLLABUS = 'REMOVE_SYLLABUS';
export const UNDO_REMOVE_SYLLABUS = 'UNDO_REMOVE_SYLLABUS';
export const SET_LESSON_INDEX = 'SET_LESSON_INDEX';
export const MARK_LESSON_COMPLETE = 'MARK_LESSON_COMPLETE';
export const UNMARK_LESSON_COMPLETE = 'UNMARK_LESSON_COMPLETE';
export const ARCHIVE_SYLLABUS = 'ARCHIVE_SYLLABUS';
export const UNARCHIVE_SYLLABUS = 'UNARCHIVE_SYLLABUS';

// ── Reader ────────────────────────────────────────────────────
export const ADD_STANDALONE_READER = 'ADD_STANDALONE_READER';
export const UPDATE_STANDALONE_READER_META = 'UPDATE_STANDALONE_READER_META';
export const REMOVE_STANDALONE_READER = 'REMOVE_STANDALONE_READER';
export const UNDO_REMOVE_STANDALONE_READER = 'UNDO_REMOVE_STANDALONE_READER';
export const SET_READER = 'SET_READER';
export const CLEAR_READER = 'CLEAR_READER';
export const LOAD_CACHED_READER = 'LOAD_CACHED_READER';
export const TOUCH_READER = 'TOUCH_READER';
export const SET_QUOTA_WARNING = 'SET_QUOTA_WARNING';
export const ARCHIVE_STANDALONE_READER = 'ARCHIVE_STANDALONE_READER';
export const UNARCHIVE_STANDALONE_READER = 'UNARCHIVE_STANDALONE_READER';
export const START_PENDING_READER = 'START_PENDING_READER';
export const CLEAR_PENDING_READER = 'CLEAR_PENDING_READER';
export const SET_EVICTED_READER_KEYS = 'SET_EVICTED_READER_KEYS';
export const RESTORE_EVICTED_READER = 'RESTORE_EVICTED_READER';

// ── Vocabulary ────────────────────────────────────────────────
export const ADD_VOCABULARY = 'ADD_VOCABULARY';
export const UPDATE_VOCAB_SRS = 'UPDATE_VOCAB_SRS';
export const CLEAR_VOCABULARY = 'CLEAR_VOCABULARY';
export const ADD_EXPORTED_WORDS = 'ADD_EXPORTED_WORDS';
export const CLEAR_EXPORTED_WORDS = 'CLEAR_EXPORTED_WORDS';

// ── Grammar ──────────────────────────────────────────────────
export const ADD_GRAMMAR = 'ADD_GRAMMAR';
export const UPDATE_GRAMMAR_SRS = 'UPDATE_GRAMMAR_SRS';
export const CLEAR_GRAMMAR = 'CLEAR_GRAMMAR';

// ── UI ────────────────────────────────────────────────────────
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

// ── Preferences ───────────────────────────────────────────────
export const SET_MAX_TOKENS = 'SET_MAX_TOKENS';
export const SET_DEFAULT_LEVEL = 'SET_DEFAULT_LEVEL';
export const SET_DEFAULT_TOPIK_LEVEL = 'SET_DEFAULT_TOPIK_LEVEL';
export const SET_DEFAULT_YUE_LEVEL = 'SET_DEFAULT_YUE_LEVEL';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_TTS_VOICE = 'SET_TTS_VOICE';
export const SET_TTS_KO_VOICE = 'SET_TTS_KO_VOICE';
export const SET_TTS_YUE_VOICE = 'SET_TTS_YUE_VOICE';
export const SET_EXPORT_SENTENCE_ROM = 'SET_EXPORT_SENTENCE_ROM';
export const SET_EXPORT_SENTENCE_TRANS = 'SET_EXPORT_SENTENCE_TRANS';
export const SET_TTS_VOICE_FOR_LANG = 'SET_TTS_VOICE_FOR_LANG';
export const SET_TTS_SPEECH_RATE = 'SET_TTS_SPEECH_RATE';
export const SET_ROMANIZATION_ON = 'SET_ROMANIZATION_ON';
export const SET_TRANSLATE_BUTTONS = 'SET_TRANSLATE_BUTTONS';
export const SET_TRANSLATE_QUESTIONS = 'SET_TRANSLATE_QUESTIONS';
export const SET_STRUCTURED_OUTPUT = 'SET_STRUCTURED_OUTPUT';
export const SET_NEW_CARDS_PER_DAY = 'SET_NEW_CARDS_PER_DAY';
export const SET_DEFAULT_LEVEL_FOR_LANG = 'SET_DEFAULT_LEVEL_FOR_LANG';
export const SET_NATIVE_LANG = 'SET_NATIVE_LANG';
export const SET_SHOW_ARCHIVED = 'SET_SHOW_ARCHIVED';

// ── Cloud ─────────────────────────────────────────────────────
export const SET_CLOUD_USER = 'SET_CLOUD_USER';
export const SET_CLOUD_SYNCING = 'SET_CLOUD_SYNCING';
export const SET_CLOUD_LAST_SYNCED = 'SET_CLOUD_LAST_SYNCED';
export const HYDRATE_FROM_CLOUD = 'HYDRATE_FROM_CLOUD';
export const MERGE_WITH_CLOUD = 'MERGE_WITH_CLOUD';
export const SET_HAS_MERGE_SNAPSHOT = 'SET_HAS_MERGE_SNAPSHOT';
export const CLEAR_MERGE_SNAPSHOT = 'CLEAR_MERGE_SNAPSHOT';
export const REVERT_MERGE = 'REVERT_MERGE';

//── Data ──────────────────────────────────────────────────────
export const RESTORE_FROM_BACKUP = 'RESTORE_FROM_BACKUP';
export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA';
export const FS_INITIALIZED = 'FS_INITIALIZED';
export const SET_SAVE_FOLDER = 'SET_SAVE_FOLDER';
export const HYDRATE_FROM_FILES = 'HYDRATE_FROM_FILES';
export const SET_LEARNING_ACTIVITY = 'SET_LEARNING_ACTIVITY';
export const LOG_ACTIVITY = 'LOG_ACTIVITY';
export const UPDATE_READING_TIME = 'UPDATE_READING_TIME';
export const LOG_READING_SESSION = 'LOG_READING_SESSION';
export const SET_WEEKLY_GOALS = 'SET_WEEKLY_GOALS';

// ── DATA_ACTIONS set (actions that bump lastModified) ─────────
export const DATA_ACTIONS = new Set([
  ADD_LEARNING_PATH, UPDATE_LEARNING_PATH, REMOVE_LEARNING_PATH,
  SET_PATH_UNIT_SYLLABUS, UPDATE_PATH_COVERAGE, EXTEND_LEARNING_PATH,
  REORDER_PATH_UNITS, UPDATE_PATH_UNIT, ARCHIVE_LEARNING_PATH, UNARCHIVE_LEARNING_PATH,
  ADD_SYLLABUS, EXTEND_SYLLABUS_LESSONS, REMOVE_SYLLABUS,
  SET_LESSON_INDEX, MARK_LESSON_COMPLETE, UNMARK_LESSON_COMPLETE,
  ADD_STANDALONE_READER, REMOVE_STANDALONE_READER, UPDATE_STANDALONE_READER_META,
  ARCHIVE_SYLLABUS, UNARCHIVE_SYLLABUS,
  ARCHIVE_STANDALONE_READER, UNARCHIVE_STANDALONE_READER,
  SET_READER, CLEAR_READER,
  ADD_VOCABULARY, CLEAR_VOCABULARY, UPDATE_VOCAB_SRS,
  ADD_EXPORTED_WORDS, CLEAR_EXPORTED_WORDS,
  ADD_GRAMMAR, UPDATE_GRAMMAR_SRS, CLEAR_GRAMMAR,
]);
